name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch: # Run workflow manually

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in Medium posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://jimmypang.medium.com/feed"
          max_post_count: 5
          comment_tag_name: "BLOG-POST-LIST"